INSERT INTO BOOK(BOOK_ID, BOOK_TITLE, BOOK_DESCRIPTION, ILLUSTRATIONS, NUMBER, NUM_PAGES, PRICE) values (1000, 'Beginning Java EE 6', 'Best Java EE book ever', TRUE , '1234-5678', 450, 49)
INSERT INTO BOOK(BOOK_ID, BOOK_TITLE, BOOK_DESCRIPTION, ILLUSTRATIONS, NUMBER, NUM_PAGES, PRICE) values (1001, 'Beginning Java EE 7', 'No, this is the best ', TRUE, '5678-9012', 550, 53)
INSERT INTO BOOK(BOOK_ID, BOOK_TITLE, BOOK_DESCRIPTION, ILLUSTRATIONS, NUMBER, NUM_PAGES, PRICE) values (1010, 'The Lord of the Rings', 'One ring to rule them all', FALSE, '9012-3456', 222, 23)
